<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BannerlordSearch.Domain\BannerlordSearch.Domain.csproj" />
    <ProjectReference Include="..\BannerlordSearch.Application\BannerlordSearch.Application.csproj" />
    <ProjectReference Include="..\BannerlordSearch.Infrastructure\BannerlordSearch.Infrastructure.csproj" />
    <ProjectReference Include="..\BannerlordSearch.Presentation\BannerlordSearch.Presentation.csproj" />
    <PackageReference Include="ModelContextProtocol" Version="0.8.0-preview.1" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.8.0-preview.1" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="xunit" Version="2.9.3"/>
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.5" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>

</Project>
